export const options = [
    {
        lable:'id',
        prop:'id'
    },
    {
        lable:'username',
        prop:'username'
    },
    {
        lable:'role_name',
        prop:'role_name'
    },
    {
        lable:'mobile',
        prop:'mobile'
    },
    {
        lable:'email',
        prop:'email'
    },
    {
        lable:'create_time',
        prop:'create_time'
    },
    {
        lable:'action',
        prop:'action'
    },
]